DELETE FROM notification_templates WHERE code IN (
    'INVOICE_REMINDER_H3_WA',
    'INVOICE_REMINDER_H1_WA',
    'INVOICE_DUE_TODAY_WA',
    'INVOICE_OVERDUE_WA',
    'SERVICE_ISOLATED_WA'
);
